import { createContext, useContext, useState, type ReactNode } from "react";

export type Lang = "es" | "en";

const translations = {
  es: {
    // Sidebar
    dashboard: "Dashboard",
    produccion: "Producción",
    compras: "Compras",
    sostenibilidad: "Sostenibilidad",
    cerrarSesion: "Cerrar sesión",
    // Dashboard
    dashboardTitle: "Dashboard Analítico",
    dashboardSub: "Consumo, desperdicio y ahorro en tiempo real",
    diario: "Diario",
    semanal: "Semanal",
    mensual: "Mensual",
    consumoTotal: "Consumo total",
    desperdicio: "Desperdicio",
    ahorroProyectado: "Ahorro proyectado",
    comidaRescatada: "Comida rescatada",
    acumuladoMes: "Acumulado del mes",
    consumoVsDesperdicio: "Consumo vs Desperdicio por Turno (kg)",
    proyeccionAhorro: "Proyección de Ahorro Mensual",
    vsAnterior: "vs sem anterior",
    reduccion: "reducción",
    vsAnteriorMes: "vs mes anterior",
    periodo: "Periodo",
    tiempo: "Tiempo",
    // Produccion
    produccionTitle: "Recomendación de Producción",
    produccionSub: "Cantidades sugeridas basadas en 187 reservas para hoy",
    reservasDia: "Reservas del día",
    reduccionPotencial: "Reducción potencial",
    itemsAceptados: "Ítems aceptados",
    item: "Ítem",
    actual: "Actual",
    recomendado: "Recomendado",
    unidad: "Unidad",
    confianza: "Confianza",
    accion: "Acción",
    aceptar: "Aceptar",
    aceptado: "✓ Aceptado",
    unidades: "unidades",
    // Compras
    comprasTitle: "Gestión de Compras",
    comprasSub: "Inventario actual y pedidos sugeridos",
    productosInventario: "Productos en inventario",
    alertasCriticas: "Alertas críticas",
    pedidosPendientes: "Pedidos pendientes",
    inventarioActual: "Inventario Actual",
    pedidoSugerido: "Pedido Sugerido",
    sku: "SKU",
    nombre: "Nombre",
    stock: "Stock",
    minimo: "Mínimo",
    estado: "Estado",
    aPedir: "A pedir",
    descargarCSV: "Descargar CSV",
    generando: "Generando...",
    subirDocumento: "Subir Documento",
    critico: "Crítico",
    // Sostenibilidad
    sostenibilidadTitle: "Reporte de Sostenibilidad",
    sostenibilidadSub: "Impacto ambiental y progreso hacia el ODS 2: Hambre Cero",
    co2Evitado: "CO₂ evitado",
    metanoEvitado: "Metano evitado",
    metaReduccion: "Meta de reducción",
    meta: "Meta",
    metaCumplida: "✅ Meta cumplida",
    enProgreso: "En progreso",
    comidaRescatadaSem: "Comida Rescatada por Semana (kg)",
    progresoMeta: "Progreso hacia la Meta",
    reduccionActual: "Reducción actual",
    equivalenciasAmbientales: "Equivalencias Ambientales",
    arboles: "árboles plantados equiv.",
    kmAuto: "km en auto evitados",
    co2Tooltip: "El CO₂ es un gas, pero sus emisiones se miden en kilogramos (kg) de equivalente de CO₂ (CO₂e) para estandarizar el impacto climático.",
    arbolesTooltip: "Basado en el CO₂ promedio que un árbol absorbe al año (aprox. 21 kg).",
    autoTooltip: "Basado en emisiones de un auto a gasolina (aprox. 0.192 kg CO₂ por km).",
    cumpliendoMeta: "Cumpliendo",
    noCumpliendoMeta: "No cumpliendo",
    leyendaColores: "Leyenda de colores",
    leyendaVerde: "Verde: Cumpliendo metas / Estado saludable",
    leyendaAmarillo: "Amarillo: Precaución / En progreso",
    leyendaRojo: "Rojo: Crítico / Requiere atención",
    // Huesped
    huespedSub: "Tu consumo responsable hace la diferencia 🌱",
    semanaRescatado: "Esta semana hemos rescatado",
    kilogramos: "kilogramos de comida",
    platosEquivalentes: "platos equivalentes",
    co2EvitadoSem: "kg CO₂ evitados",
    ods2: "Juntos contribuimos al ODS 2: Hambre Cero",
    ods2Sub: "Cada porción que sirves con conciencia ayuda a reducir el desperdicio alimentario global.",
    powered: "Powered by FullCycle Solutions • Universidad de La Sabana",
    // Login
    iniciarSesion: "Iniciar sesión",
    loginSub: "Ingresa tus credenciales para acceder al sistema",
    correo: "Correo electrónico",
    contrasena: "Contraseña",
    ingresar: "Ingresar",
    credencialsPrueba: "Credenciales de prueba:",
    correoObligatorio: "El correo es obligatorio",
    correoInvalido: "Correo inválido",
    contrasenaObligatoria: "La contraseña es obligatoria",
    contrasenaMin: "Mínimo 6 caracteres",
    usuarioNoEncontrado: "Usuario no encontrado",
    contrasenaIncorrecta: "Contraseña incorrecta",
    errorLogin: "Error al iniciar sesión",
    loginHeroSub: "Reduciendo el desperdicio alimentario en hoteles y cruceros. Alineados con el ODS 2: Hambre Cero.",
    kgRescatados: "kg rescatados",
    kgCO2: "kg CO₂ evitados",
    // DocumentUploader
    subirDocTitle: "Subir Documento de Inventario",
    subirDocDesc: "Sube un archivo CSV o Excel (.xlsx) con columnas: SKU, Nombre, Stock, Mínimo, Unidad",
    arrastraCSV: "Arrastra un archivo CSV o Excel aquí",
    haceClic: "o haz clic para seleccionar",
    analizando: "Analizando...",
    archivoAnalizado: "analizado correctamente",
    productos: "Productos",
    criticos: "Críticos",
    saludables: "Saludables",
    pedidoAutoGenerado: "Pedido Sugerido (Auto-generado)",
    verInventario: "Ver inventario completo",
    items: "items",
    formatoNoSoportado: "Formato no soportado. Por favor sube un archivo CSV o Excel.",
    descargarPlantilla: "Descargar Plantilla",
    archivoVacio: "El archivo está vacío o no tiene datos válidos.",
    sinColumnasSKU: "No se encontró la columna SKU. Asegúrate de que el archivo tenga columnas: SKU, Nombre, Stock, Mínimo, Unidad.",
    sinDatosValidos: "No se pudieron extraer datos válidos. Revisa las columnas del archivo.",
    errorProcesar: "Error al procesar el archivo. Verifica el formato.",
    errorLeer: "Error al leer el archivo.",
    masDe50: "⚠️ Más del 50% del inventario está en estado crítico",
    productosBajoMinimo: "producto(s) por debajo del stock mínimo",
    // Estado de pedidos
    pendiente: "Pendiente",
    enviado: "Enviado",
    recibido: "Recibido",
    pagado: "Pagado",
    // Pagos a proveedores
    pagarProveedor: "Pagar proveedor",
    registrarPago: "Registrar pago",
    pagoTitulo: "Registrar Pago al Proveedor",
    pagoDesc: "Completa los datos del pago. Se simulará el envío de un email de confirmación al proveedor.",
    proveedor: "Proveedor",
    emailProveedor: "Email del proveedor",
    montoTotal: "Monto total (COP)",
    metodoPago: "Método de pago",
    transferencia: "Transferencia bancaria",
    cheque: "Cheque",
    efectivo: "Efectivo",
    tarjeta: "Tarjeta de crédito",
    referenciaPago: "Referencia / N° de orden",
    cancelar: "Cancelar",
    confirmarPago: "Confirmar pago",
    pagoRegistrado: "Pago registrado exitosamente",
    emailSimulado: "Email enviado a",
    montoObligatorio: "Ingresa el monto",
    referenciaObligatoria: "Ingresa la referencia",
    historialPagos: "Historial de Pagos",
    fechaPago: "Fecha de pago",
    monto: "Monto",
    referencia: "Referencia",
    metodo: "Método",
    verDetallePago: "Ver detalle",
    pagosTitulo: "Pagos a Proveedores",
    pagosPendientes: "Pagos pendientes",
    marcarEnviado: "Marcar enviado",
    marcarRecibido: "Marcar recibido",
    sinPedidos: "Sin pedidos activos",
    verPreviewEmail: "Ver preview email",
    // Tarjetas de pago
    seleccionarTarjeta: "Método de pago",
    datosPago: "Datos del pago",
    previewEmail: "Confirmar y enviar",
    agregarTarjeta: "Agregar tarjeta",
    agregarOtraTarjeta: "Agregar otra tarjeta",
    sinTarjetas: "Sin métodos de pago guardados",
    agregarTarjetaParaPagar: "Agrega una tarjeta para continuar con el pago",
    numeroTarjeta: "Número de tarjeta",
    titularTarjeta: "Titular de la tarjeta",
    vencimiento: "Vencimiento",
    guardarTarjeta: "Guardar tarjeta",
    tarjetaGuardada: "Tarjeta guardada exitosamente",
    tarjetaSegura: "Solo guardamos los últimos 4 dígitos. Nunca el número completo.",
    establecerPrincipal: "Establecer como método principal",
    continuar: "Continuar",
    atras: "Atrás",
    pagoSeguro: "Pago seguro · integración Stripe disponible para producción",
    errorNumeroTarjeta: "Número de tarjeta inválido",
    errorTitular: "Ingresa el nombre del titular",
    errorExpiry: "Fecha de vencimiento inválida",
    errorCvv: "CVV inválido",
    // Indicadores de datos
    datosDemo: "Datos de ejemplo",
    datosCargados: "Datos cargados",
    // Registro de desperdicio
    registrarDesperdicio: "Registrar Desperdicio",
    cuantoSobro: "¿Cuánto sobró?",
    registrar: "Registrar",
    desperdicioRegistrado: "Desperdicio registrado",
    registrosHoy: "Registros de hoy",
    sinRegistros: "Sin registros aún",
    cantidadKg: "Cantidad (kg)",
  },
  en: {
    // Sidebar
    dashboard: "Dashboard",
    produccion: "Production",
    compras: "Purchasing",
    sostenibilidad: "Sustainability",
    cerrarSesion: "Log out",
    // Dashboard
    dashboardTitle: "Analytics Dashboard",
    dashboardSub: "Consumption, waste and savings in real time",
    diario: "Daily",
    semanal: "Weekly",
    mensual: "Monthly",
    consumoTotal: "Total consumption",
    desperdicio: "Waste",
    ahorroProyectado: "Projected savings",
    comidaRescatada: "Rescued food",
    acumuladoMes: "Month accumulated",
    consumoVsDesperdicio: "Consumption vs Waste by Shift (kg)",
    proyeccionAhorro: "Monthly Savings Projection",
    vsAnterior: "vs prev week",
    reduccion: "reduction",
    vsAnteriorMes: "vs prev month",
    periodo: "Period",
    tiempo: "Time",
    // Produccion
    produccionTitle: "Production Recommendation",
    produccionSub: "Suggested quantities based on 187 reservations for today",
    reservasDia: "Today's reservations",
    reduccionPotencial: "Potential reduction",
    itemsAceptados: "Accepted items",
    item: "Item",
    actual: "Current",
    recomendado: "Recommended",
    unidad: "Unit",
    confianza: "Confidence",
    accion: "Action",
    aceptar: "Accept",
    aceptado: "✓ Accepted",
    unidades: "units",
    // Compras
    comprasTitle: "Purchasing Management",
    comprasSub: "Current inventory and suggested orders",
    productosInventario: "Inventory products",
    alertasCriticas: "Critical alerts",
    pedidosPendientes: "Pending orders",
    inventarioActual: "Current Inventory",
    pedidoSugerido: "Suggested Order",
    sku: "SKU",
    nombre: "Name",
    stock: "Stock",
    minimo: "Minimum",
    estado: "Status",
    aPedir: "To order",
    descargarCSV: "Download CSV",
    generando: "Generating...",
    subirDocumento: "Upload Document",
    critico: "Critical",
    // Sostenibilidad
    sostenibilidadTitle: "Sustainability Report",
    sostenibilidadSub: "Environmental impact and progress toward SDG 2: Zero Hunger",
    co2Evitado: "CO₂ avoided",
    metanoEvitado: "Methane avoided",
    metaReduccion: "Reduction goal",
    meta: "Goal",
    metaCumplida: "✅ Goal achieved",
    enProgreso: "In progress",
    comidaRescatadaSem: "Rescued Food per Week (kg)",
    progresoMeta: "Progress toward Goal",
    reduccionActual: "Current reduction",
    equivalenciasAmbientales: "Environmental Equivalences",
    arboles: "equivalent trees planted",
    kmAuto: "km by car avoided",
    co2Tooltip: "CO₂ is a gas, but its emissions are measured in kilograms (kg) of CO₂ equivalent (CO₂e) to standardize climate impact.",
    arbolesTooltip: "Based on the average CO₂ a tree absorbs per year (approx. 21 kg).",
    autoTooltip: "Based on emissions of a gasoline car (approx. 0.192 kg CO₂ per km).",
    cumpliendoMeta: "Meeting goal",
    noCumpliendoMeta: "Not meeting goal",
    leyendaColores: "Color Legend",
    leyendaVerde: "Green: Meeting goals / Healthy status",
    leyendaAmarillo: "Yellow: Warning / In progress",
    leyendaRojo: "Red: Critical / Requires attention",
    // Huesped
    huespedSub: "Your responsible consumption makes a difference 🌱",
    semanaRescatado: "This week we have rescued",
    kilogramos: "kilograms of food",
    platosEquivalentes: "equivalent meals",
    co2EvitadoSem: "kg CO₂ avoided",
    ods2: "Together we contribute to SDG 2: Zero Hunger",
    ods2Sub: "Every portion you serve consciously helps reduce global food waste.",
    powered: "Powered by FullCycle Solutions • Universidad de La Sabana",
    // Login
    iniciarSesion: "Sign in",
    loginSub: "Enter your credentials to access the system",
    correo: "Email",
    contrasena: "Password",
    ingresar: "Sign in",
    credencialsPrueba: "Test credentials:",
    correoObligatorio: "Email is required",
    correoInvalido: "Invalid email",
    contrasenaObligatoria: "Password is required",
    contrasenaMin: "Minimum 6 characters",
    usuarioNoEncontrado: "User not found",
    contrasenaIncorrecta: "Incorrect password",
    errorLogin: "Login error",
    loginHeroSub: "Reducing food waste in hotels and cruise ships. Aligned with SDG 2: Zero Hunger.",
    kgRescatados: "kg rescued",
    kgCO2: "kg CO₂ avoided",
    // DocumentUploader
    subirDocTitle: "Upload Inventory Document",
    subirDocDesc: "Upload a CSV or Excel (.xlsx) file with columns: SKU, Name, Stock, Minimum, Unit",
    arrastraCSV: "Drag a CSV or Excel file here",
    haceClic: "or click to select",
    analizando: "Analyzing...",
    archivoAnalizado: "analyzed successfully",
    productos: "Products",
    criticos: "Critical",
    saludables: "Healthy",
    pedidoAutoGenerado: "Suggested Order (Auto-generated)",
    verInventario: "View full inventory",
    items: "items",
    formatoNoSoportado: "Unsupported format. Please upload a CSV or Excel file.",
    descargarPlantilla: "Download Template",
    archivoVacio: "The file is empty or has no valid data.",
    sinColumnasSKU: "SKU column not found. Make sure the file has columns: SKU, Name, Stock, Minimum, Unit.",
    sinDatosValidos: "Could not extract valid data. Check the file columns.",
    errorProcesar: "Error processing the file. Check the format.",
    errorLeer: "Error reading the file.",
    masDe50: "⚠️ More than 50% of inventory is in critical status",
    productosBajoMinimo: "product(s) below minimum stock",
    // Estado de pedidos
    pendiente: "Pending",
    enviado: "Shipped",
    recibido: "Received",
    pagado: "Paid",
    // Pagos a proveedores
    pagarProveedor: "Pay supplier",
    registrarPago: "Register payment",
    pagoTitulo: "Register Supplier Payment",
    pagoDesc: "Fill in the payment details. A confirmation email will be simulated to the supplier.",
    proveedor: "Supplier",
    emailProveedor: "Supplier email",
    montoTotal: "Total amount (COP)",
    metodoPago: "Payment method",
    transferencia: "Bank transfer",
    cheque: "Check",
    efectivo: "Cash",
    tarjeta: "Credit card",
    referenciaPago: "Reference / Order #",
    cancelar: "Cancel",
    confirmarPago: "Confirm payment",
    pagoRegistrado: "Payment registered successfully",
    emailSimulado: "Email sent to",
    montoObligatorio: "Enter amount",
    referenciaObligatoria: "Enter reference",
    historialPagos: "Payment History",
    fechaPago: "Payment date",
    monto: "Amount",
    referencia: "Reference",
    metodo: "Method",
    verDetallePago: "View detail",
    pagosTitulo: "Supplier Payments",
    pagosPendientes: "Pending payments",
    marcarEnviado: "Mark as shipped",
    marcarRecibido: "Mark as received",
    sinPedidos: "No active orders",
    verPreviewEmail: "Preview email",
    // Tarjetas de pago
    seleccionarTarjeta: "Payment method",
    datosPago: "Payment details",
    previewEmail: "Confirm & send",
    agregarTarjeta: "Add card",
    agregarOtraTarjeta: "Add another card",
    sinTarjetas: "No saved payment methods",
    agregarTarjetaParaPagar: "Add a card to continue with the payment",
    numeroTarjeta: "Card number",
    titularTarjeta: "Cardholder name",
    vencimiento: "Expiry",
    guardarTarjeta: "Save card",
    tarjetaGuardada: "Card saved successfully",
    tarjetaSegura: "We only store the last 4 digits. Never the full number.",
    establecerPrincipal: "Set as default payment method",
    continuar: "Continue",
    atras: "Back",
    pagoSeguro: "Secure payment · Stripe integration available for production",
    errorNumeroTarjeta: "Invalid card number",
    errorTitular: "Enter the cardholder name",
    errorExpiry: "Invalid expiry date",
    errorCvv: "Invalid CVV",
    // Indicadores de datos
    datosDemo: "Sample data",
    datosCargados: "Loaded data",
    // Registro de desperdicio
    registrarDesperdicio: "Register Waste",
    cuantoSobro: "How much was left over?",
    registrar: "Register",
    desperdicioRegistrado: "Waste registered",
    registrosHoy: "Today's records",
    sinRegistros: "No records yet",
    cantidadKg: "Amount (kg)",
  },
} as const;

type Translations = typeof translations.es;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("es");
  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] as Translations }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be inside LangProvider");
  return ctx;
}
