import { createContext, useContext, useState, type ReactNode } from "react";

export type Lang = "es" | "en";

const translations = {
  es: {
    // Sidebar
    dashboard: "Dashboard",
    produccion: "Producción",
    compras: "Compras",
    sostenibilidad: "Sostenibilidad",
    cerrarSesion: "Cerrar sesión",
    // Dashboard
    dashboardTitle: "Dashboard Analítico",
    dashboardSub: "Consumo, desperdicio y ahorro en tiempo real",
    diario: "Diario",
    semanal: "Semanal",
    mensual: "Mensual",
    consumoTotal: "Consumo total",
    desperdicio: "Desperdicio",
    ahorroProyectado: "Ahorro proyectado",
    comidaRescatada: "Comida rescatada",
    acumuladoMes: "Acumulado del mes",
    consumoVsDesperdicio: "Consumo vs Desperdicio por Turno (kg)",
    proyeccionAhorro: "Proyección de Ahorro Mensual",
    vsAnterior: "vs sem anterior",
    reduccion: "reducción",
    vsAnteriorMes: "vs mes anterior",
    // Produccion
    produccionTitle: "Recomendación de Producción",
    produccionSub: "Cantidades sugeridas basadas en 187 reservas para hoy",
    reservasDia: "Reservas del día",
    reduccionPotencial: "Reducción potencial",
    itemsAceptados: "Ítems aceptados",
    item: "Ítem",
    actual: "Actual",
    recomendado: "Recomendado",
    unidad: "Unidad",
    confianza: "Confianza",
    accion: "Acción",
    aceptar: "Aceptar",
    aceptado: "✓ Aceptado",
    unidades: "unidades",
    // Compras
    comprasTitle: "Gestión de Compras",
    comprasSub: "Inventario actual y pedidos sugeridos",
    productosInventario: "Productos en inventario",
    alertasCriticas: "Alertas críticas",
    pedidosPendientes: "Pedidos pendientes",
    inventarioActual: "Inventario Actual",
    pedidoSugerido: "Pedido Sugerido",
    sku: "SKU",
    nombre: "Nombre",
    stock: "Stock",
    minimo: "Mínimo",
    estado: "Estado",
    aPedir: "A pedir",
    descargarCSV: "Descargar CSV",
    generando: "Generando...",
    subirDocumento: "Subir Documento",
    critico: "Crítico",
    // Sostenibilidad
    sostenibilidadTitle: "Reporte de Sostenibilidad",
    sostenibilidadSub: "Impacto ambiental y progreso hacia el ODS 2: Hambre Cero",
    co2Evitado: "CO₂ evitado",
    metanoEvitado: "Metano evitado",
    metaReduccion: "Meta de reducción",
    meta: "Meta",
    metaCumplida: "✅ Meta cumplida",
    enProgreso: "En progreso",
    comidaRescatadaSem: "Comida Rescatada por Semana (kg)",
    progresoMeta: "Progreso hacia la Meta",
    reduccionActual: "Reducción actual",
    equivalenciasAmbientales: "Equivalencias Ambientales",
    arboles: "árboles plantados equiv.",
    kmAuto: "km en auto evitados",
    // Huesped
    huespedSub: "Tu consumo responsable hace la diferencia 🌱",
    semanaRescatado: "Esta semana hemos rescatado",
    kilogramos: "kilogramos de comida",
    platosEquivalentes: "platos equivalentes",
    co2EvitadoSem: "kg CO₂ evitados",
    ods2: "Juntos contribuimos al ODS 2: Hambre Cero",
    ods2Sub: "Cada porción que sirves con conciencia ayuda a reducir el desperdicio alimentario global.",
    powered: "Powered by FullCycle Solutions • Universidad de La Sabana",
    // Login
    iniciarSesion: "Iniciar sesión",
    loginSub: "Ingresa tus credenciales para acceder al sistema",
    correo: "Correo electrónico",
    contrasena: "Contraseña",
    ingresar: "Ingresar",
    credencialsPrueba: "Credenciales de prueba:",
    correoObligatorio: "El correo es obligatorio",
    correoInvalido: "Correo inválido",
    contrasenaObligatoria: "La contraseña es obligatoria",
    contrasenaMin: "Mínimo 6 caracteres",
    usuarioNoEncontrado: "Usuario no encontrado",
    contrasenaIncorrecta: "Contraseña incorrecta",
    errorLogin: "Error al iniciar sesión",
    loginHeroSub: "Reduciendo el desperdicio alimentario en hoteles y cruceros. Alineados con el ODS 2: Hambre Cero.",
    kgRescatados: "kg rescatados",
    kgCO2: "kg CO₂ evitados",
    // DocumentUploader
    subirDocTitle: "Subir Documento de Inventario",
    subirDocDesc: "Sube un archivo CSV con columnas: SKU, Nombre, Stock, Mínimo, Unidad",
    arrastraCSV: "Arrastra un archivo CSV aquí",
    haceClic: "o haz clic para seleccionar",
    analizando: "Analizando...",
    archivoAnalizado: "analizado correctamente",
    productos: "Productos",
    criticos: "Críticos",
    saludables: "Saludables",
    pedidoAutoGenerado: "Pedido Sugerido (Auto-generado)",
    verInventario: "Ver inventario completo",
    items: "items",
    formatoNoSoportado: "Formato no soportado. Por favor sube un archivo CSV.",
    archivoVacio: "El archivo está vacío o no tiene datos válidos.",
    sinColumnasSKU: "No se encontró la columna SKU. Asegúrate de que el archivo tenga columnas: SKU, Nombre, Stock, Mínimo, Unidad.",
    sinDatosValidos: "No se pudieron extraer datos válidos. Revisa las columnas del archivo.",
    errorProcesar: "Error al procesar el archivo. Verifica el formato.",
    errorLeer: "Error al leer el archivo.",
    masDe50: "⚠️ Más del 50% del inventario está en estado crítico",
    productosBajoMinimo: "producto(s) por debajo del stock mínimo",
  },
  en: {
    // Sidebar
    dashboard: "Dashboard",
    produccion: "Production",
    compras: "Purchasing",
    sostenibilidad: "Sustainability",
    cerrarSesion: "Log out",
    // Dashboard
    dashboardTitle: "Analytics Dashboard",
    dashboardSub: "Consumption, waste and savings in real time",
    diario: "Daily",
    semanal: "Weekly",
    mensual: "Monthly",
    consumoTotal: "Total consumption",
    desperdicio: "Waste",
    ahorroProyectado: "Projected savings",
    comidaRescatada: "Rescued food",
    acumuladoMes: "Month accumulated",
    consumoVsDesperdicio: "Consumption vs Waste by Shift (kg)",
    proyeccionAhorro: "Monthly Savings Projection",
    vsAnterior: "vs prev week",
    reduccion: "reduction",
    vsAnteriorMes: "vs prev month",
    // Produccion
    produccionTitle: "Production Recommendation",
    produccionSub: "Suggested quantities based on 187 reservations for today",
    reservasDia: "Today's reservations",
    reduccionPotencial: "Potential reduction",
    itemsAceptados: "Accepted items",
    item: "Item",
    actual: "Current",
    recomendado: "Recommended",
    unidad: "Unit",
    confianza: "Confidence",
    accion: "Action",
    aceptar: "Accept",
    aceptado: "✓ Accepted",
    unidades: "units",
    // Compras
    comprasTitle: "Purchasing Management",
    comprasSub: "Current inventory and suggested orders",
    productosInventario: "Inventory products",
    alertasCriticas: "Critical alerts",
    pedidosPendientes: "Pending orders",
    inventarioActual: "Current Inventory",
    pedidoSugerido: "Suggested Order",
    sku: "SKU",
    nombre: "Name",
    stock: "Stock",
    minimo: "Minimum",
    estado: "Status",
    aPedir: "To order",
    descargarCSV: "Download CSV",
    generando: "Generating...",
    subirDocumento: "Upload Document",
    critico: "Critical",
    // Sostenibilidad
    sostenibilidadTitle: "Sustainability Report",
    sostenibilidadSub: "Environmental impact and progress toward SDG 2: Zero Hunger",
    co2Evitado: "CO₂ avoided",
    metanoEvitado: "Methane avoided",
    metaReduccion: "Reduction goal",
    meta: "Goal",
    metaCumplida: "✅ Goal achieved",
    enProgreso: "In progress",
    comidaRescatadaSem: "Rescued Food per Week (kg)",
    progresoMeta: "Progress toward Goal",
    reduccionActual: "Current reduction",
    equivalenciasAmbientales: "Environmental Equivalences",
    arboles: "equivalent trees planted",
    kmAuto: "km by car avoided",
    // Huesped
    huespedSub: "Your responsible consumption makes a difference 🌱",
    semanaRescatado: "This week we have rescued",
    kilogramos: "kilograms of food",
    platosEquivalentes: "equivalent meals",
    co2EvitadoSem: "kg CO₂ avoided",
    ods2: "Together we contribute to SDG 2: Zero Hunger",
    ods2Sub: "Every portion you serve consciously helps reduce global food waste.",
    powered: "Powered by FullCycle Solutions • Universidad de La Sabana",
    // Login
    iniciarSesion: "Sign in",
    loginSub: "Enter your credentials to access the system",
    correo: "Email",
    contrasena: "Password",
    ingresar: "Sign in",
    credencialsPrueba: "Test credentials:",
    correoObligatorio: "Email is required",
    correoInvalido: "Invalid email",
    contrasenaObligatoria: "Password is required",
    contrasenaMin: "Minimum 6 characters",
    usuarioNoEncontrado: "User not found",
    contrasenaIncorrecta: "Incorrect password",
    errorLogin: "Login error",
    loginHeroSub: "Reducing food waste in hotels and cruise ships. Aligned with SDG 2: Zero Hunger.",
    kgRescatados: "kg rescued",
    kgCO2: "kg CO₂ avoided",
    // DocumentUploader
    subirDocTitle: "Upload Inventory Document",
    subirDocDesc: "Upload a CSV file with columns: SKU, Name, Stock, Minimum, Unit",
    arrastraCSV: "Drag a CSV file here",
    haceClic: "or click to select",
    analizando: "Analyzing...",
    archivoAnalizado: "analyzed successfully",
    productos: "Products",
    criticos: "Critical",
    saludables: "Healthy",
    pedidoAutoGenerado: "Suggested Order (Auto-generated)",
    verInventario: "View full inventory",
    items: "items",
    formatoNoSoportado: "Unsupported format. Please upload a CSV file.",
    archivoVacio: "The file is empty or has no valid data.",
    sinColumnasSKU: "SKU column not found. Make sure the file has columns: SKU, Name, Stock, Minimum, Unit.",
    sinDatosValidos: "Could not extract valid data. Check the file columns.",
    errorProcesar: "Error processing the file. Check the format.",
    errorLeer: "Error reading the file.",
    masDe50: "⚠️ More than 50% of inventory is in critical status",
    productosBajoMinimo: "product(s) below minimum stock",
  },
} as const;

type Translations = typeof translations.es;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("es");
  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] as Translations }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be inside LangProvider");
  return ctx;
}
