/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SostenibilidadRouteImport } from './routes/sostenibilidad'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ProduccionRouteImport } from './routes/produccion'
import { Route as HuespedRouteImport } from './routes/huesped'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as IndexRouteImport } from './routes/index'

const SostenibilidadRoute = SostenibilidadRouteImport.update({
  id: '/sostenibilidad',
  path: '/sostenibilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionRoute = ProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => rootRouteImport,
} as any)
const HuespedRoute = HuespedRouteImport.update({
  id: '/huesped',
  path: '/huesped',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/dashboard': typeof DashboardRoute
  '/huesped': typeof HuespedRoute
  '/produccion': typeof ProduccionRoute
  '/recursos': typeof RecursosRoute
  '/sostenibilidad': typeof SostenibilidadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/dashboard': typeof DashboardRoute
  '/huesped': typeof HuespedRoute
  '/produccion': typeof ProduccionRoute
  '/recursos': typeof RecursosRoute
  '/sostenibilidad': typeof SostenibilidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/dashboard': typeof DashboardRoute
  '/huesped': typeof HuespedRoute
  '/produccion': typeof ProduccionRoute
  '/recursos': typeof RecursosRoute
  '/sostenibilidad': typeof SostenibilidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compras'
    | '/dashboard'
    | '/huesped'
    | '/produccion'
    | '/recursos'
    | '/sostenibilidad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compras'
    | '/dashboard'
    | '/huesped'
    | '/produccion'
    | '/recursos'
    | '/sostenibilidad'
  id:
    | '__root__'
    | '/'
    | '/compras'
    | '/dashboard'
    | '/huesped'
    | '/produccion'
    | '/recursos'
    | '/sostenibilidad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComprasRoute: typeof ComprasRoute
  DashboardRoute: typeof DashboardRoute
  HuespedRoute: typeof HuespedRoute
  ProduccionRoute: typeof ProduccionRoute
  RecursosRoute: typeof RecursosRoute
  SostenibilidadRoute: typeof SostenibilidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sostenibilidad': {
      id: '/sostenibilidad'
      path: '/sostenibilidad'
      fullPath: '/sostenibilidad'
      preLoaderRoute: typeof SostenibilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion': {
      id: '/produccion'
      path: '/produccion'
      fullPath: '/produccion'
      preLoaderRoute: typeof ProduccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huesped': {
      id: '/huesped'
      path: '/huesped'
      fullPath: '/huesped'
      preLoaderRoute: typeof HuespedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComprasRoute: ComprasRoute,
  DashboardRoute: DashboardRoute,
  HuespedRoute: HuespedRoute,
  ProduccionRoute: ProduccionRoute,
  RecursosRoute: RecursosRoute,
  SostenibilidadRoute: SostenibilidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
